### ISSUE TITLE
Needless presence of Gemfile.lock

### ISSUE THREAD

**Issue by filipenasc** [ResultadosDigitais/rdstation-ruby-client#11]
For reference, see this [Yehuda Katz's blog post](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/).

> Do not check your Gemfile.lock into version control, since it enforces precision that does not exist in the gem command, which is used to install gems in practice.

The reason why it's a good practice to not checking the `Gemfile.lock` into your version control, is that we don't need to worry about the dependecies versions which the required gems needs.

For example: this gem depends on `httparty`, which is declared in the gemspec file. The `httparty` has a dependency from `json (~> 1.8)`, in turn.

For us, does not matter if the `httparty` is installing the version 1.8 from the `json` gem, or another compatible version. We only need to worry about the `httparty` version.

**Comment by rafaelhancke** [comment]
Gemfile.lock removed according to the best practices for a gem developing.
