### ISSUE TITLE
V2 Interface Design Proposal

### ISSUE THREAD

**Issue by filipenasc** [ResultadosDigitais/rdstation-ruby-client#21]
## The client

In the version 1.x.x, every request should be called behind its own class, for example: `RDStation::Contacts.new('access-token').by_uuid('uuid')`.

The issue here is that every time I call a different endpoint, I need to pass the access token again.

The proposal now is to have a client which receives the access token once, and that client is responsible for making all the requests (although the implementation keeps in distinct classes)

For example:

```ruby
client = RDStation::Client.new(access_token: 'my-access-token')
```

### RD Station endpoints

**1. Account Info**

GET https://api.rd.services/marketing/account_info

```ruby
client.account_info
```

**2. Tracking Code**

GET https://api.rd.services/marketing/tracking_code

```ruby
client.tracking_code
```

**3. Contacts**

3.1. Find a contact by its key (currently accepts uuid and email):

GET https://api.rd.services/platform/contacts/{uuid}
GET https://api.rd.services/platform/contacts/email:{e-mail}

```ruby
client.find_contact_by(uuid: 'UUID')
client.find_contact_by(email: 'email@example.org')
```

3.2. Upsert contact

PATCH https://api.rd.services/platform/contacts/

```ruby
client.upsert_contact(email: 'email@example.org', new_payload)
```

When the key is invalid (different from `uuid` or `email`), we raise an exception.

**4. Events**

```ruby
client.create_event(event_payload)
```

**5. Fields**

```ruby
client.account_fields
client.create_field(field)
client.upsert_field(field)
client.delete_field(field_uuid)
```

**6. Webhooks**

```ruby
client.webhooks
client.create_webhook(webhook)
client.update_webhook(webhook)
client.delete_webhook(webhook_uuid)
```

Another benefit of this new approach is to hide the REST details from the users. They don't need to care if the request method is POST or PUT, they just use pure Ruby and that's it.

I am currently thinking better about this approach. Any ideas on how to improve that? Is that good enough?

**Comment by nandosousafr** [comment]
I would suggest a simple modification:

```ruby
client.webhooks #=> returns RDSM::WebhooksService
client.webhooks.all #=> list all
client.webhooks.create(params)
client.webhooks.delete(webhook_uuid)
```

This concept can be applied to contacts, events and so on.

**Comment by joaohornburg** [comment]
Closed by https://github.com/ResultadosDigitais/rdstation-ruby-client/pull/40
