### ISSUE TITLE
Change Lead method is missing on the latest released version

### ISSUE THREAD

**Issue by alessandrostein** [ResultadosDigitais/rdstation-ruby-client#3]
Hey guys,

I'm trying RDStation API but I notice that version 0.0.1 released on Rubygems doesn't have the latest commits that adds the method #change_lead. Could you release a new version?

Currently I'm using the Client API from the branch master.

Thanks.

**Comment by pcasaretto** [comment]
Done! I've just released v0.0.2 to Rubygems. :)
