### ISSUE TITLE
Add default error for unknown error codes

### ISSUE THREAD

**Issue by omar10594** [ResultadosDigitais/rdstation-ruby-client#52]
Hi, I just updated the gem recently and I started to get an exception in the error handler class when the response code is not in the list of know error codes.

# Expected Behavior

I think there should be a default error class, that we can use for any other status code.

# Current Behavior

Looks like the method `error_class` returns nil because the response code is not in the list of know error codes.

https://github.com/ResultadosDigitais/rdstation-ruby-client/blob/fba83dff8868952da41a2c4ac3ab08dcec7caaff/lib/rdstation/error_handler.rb#L24-L41

With the current behavior I can't get the data of the error response to show more information about the error, this make me harder to provide information about how reproduce the error.

## Context
* Ruby Version: 2.5.0
* Rails Version: 5.2.2.1

## Failure Logs

```
NoMethodError: undefined method `<' for nil:NilClass
lib/rdstation/error_handler.rb:13 raise_error
```

**Comment by joaohornburg** [comment]
Thanks for reporting this @omar10594 We'll take a look.

**Comment by rafaelhancke** [comment]
@omar10594 New version has been released:
