### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lypborges** [ResultadosDigitais/rdstation-ruby-client#6]
Hello! Congrats for this gem! Nice job!

I have few questions.

1 - When I call create_lead I`m passing :lifecycle_stage => 1, but when a look at RDStation it's like Lead (0). I need to create as Qualify Lead, because it's a trial user.  It's possible? How?

2 - I also need to send telephone and adress from the company, how should be my Hash?

3 - It's possible to update all information when a call change_lead? Because I'm changing the name, but it's not updating on RDStation app.

4 - How can I get a lead?

Here is my Hash:

	lead = {:email => "roberval@mailinator.com", :nome =>  "Roberval", :celular => "4888333345", :telefone => "4888333345",:cidade => "Florianopolis", :estado => "SC",:empresa => "Zinga Palace", :lifecycle_stage => 1,:cargo => 'Proprietário', identificador: 'trial users'}

**Comment by pcasaretto** [comment]
Hi @lypborges 

I wouldn't call this gem nice but thanks! :)
Regarding your questions:

1. It's not possible as of now. You'll need to use the update endpoint to update the lifecycle_stage afterwards. As you will probably find out, you may have to wait a bit for the Lead to actually get created (job procesing delay) to update it.
2. I believe you can use `endereco-da-empresa` for the address. Not sure about the telephone.
3. To update the name, submit another create request using the same email. This will unfortunately generate another conversion on Lead.
4. Right now, you cant.

As you can see, the API is currently in an infant stage. We have plans for an overhaul but I'm not sure when it will happen.
