### ISSUE TITLE
Can't pass "+" (plus) in field name

### ISSUE THREAD

**Issue by lucassch** [ResultadosDigitais/rdstation-ruby-client#7]
Code: 

``` ruby
rdstation_client.create_lead({
      :"email" => email,
      :"Recebe informações do Educar+?" => rd_matters,
      ...
    })
```

When i go to RD to see the conversion, the plus is missing:
![image](https://cloud.githubusercontent.com/assets/4160094/18681159/2c5dd542-7f3d-11e6-8f0e-3cc5f0d2579e.png)

**Comment by nandosousafr** [comment]
Hi @lucassch.

Sorry about that.

Somehow HTTParty is parsing and removing the `+` character from fields before the request.

The CURL version works fine.

```bash
$ curl -v -X POST https://www.rdstation.com.br/api/1.2/conversions \ 
--data '{"token_rdstation":"xxx", "email": "email", "Educar+?": "test", "identificador": "test1"}' \
-H "Content-Type: application/json"
```

**Comment by filipenasc** [comment]
Closing this issue since there was no interaction since 2016. If you notice the problem still happening, you can reopen that.
